name: 📝 Generate README

inputs:
  token:
    description: 'GitHub PAT token'
    required: true
  commit_message:
    description: 'Commit message'
    required: false
    default: 'docs: update README.md'
  output:
    description: 'Output file'
    required: false
    default: 'README.md'
  template:
    description: 'Template file'
    required: false
    default: 'README.tmpl.md'
  files:
    description: 'Files to include'
    required: false
    default: 'docker-compose.yml'
  git_user:
    description: 'GitHub user'
    required: false
    default: 'github-actions[bot]'
  git_email:
    description: 'GitHub email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

runs:
  using: composite

  steps:
    - name: 🐍 Install Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: 'pypy3.13' 
        cache: 'pip'

    - name: 📦 Install PyYAML
      shell: bash
      run: |
        pip install -r requirements.txt
        
    - name: 📝 Generate README
      shell: bash
      run: |
        python ${{ github.action_path }}/generate.py \
          --ouput ${{ inputs.output }} \
          --template ${{ inputs.template }} \
          ${{ inputs.files }}

    - name: 🚀 Commit & Push README
      shell: bash
      run: |
        shopt -s globstar nullglob
        git pull
        git config --global user.name '${{ inputs.git_user }}'
        git config --global user.email '${{ inputs.git_email }}'
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/$GITHUB_REPOSITORY
        git add ${{ inputs.output }}
        git commit -m "${{ inputs.commit_message }}" || true
        git push
        shopt -u globstar nullglob
