name: 🤖 Automated Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 🤖 Run Renovate
        uses: renovatebot/github-action@8b7941943a108b2cc2150730963164aa8baeab8c # v44.2.2
        with:
          configurationFile: renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_PIN_DIGESTS: true
